
name: Automation Tests - Keeggo

on: 
  push:
    branches:
      - main


jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npx cypress run --record --key 42556648-1e48-4b1a-b6ec-7ffafb696d71
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}